language: generic

env:
  matrix:
    - ATOM_CHANNEL=stable
    - ATOM_CHANNEL=beta

script:
  - curl -s -O https://raw.githubusercontent.com/atom/ci/master/build-package.sh
  - chmod u+x build-package.sh
  - ./build-package.sh

os:
  - osx
sudo: false
dist: trusty
addons:
  apt:
    packages:
    - g++-6
    - fakeroot
    - git
    - libsecret-1-dev

git:
  depth: 10

notifications:
  email:
    on_success: never
    on_failure: change
